---
  - name: print the facts
    hosts: servera
    gather_facts: false
    tasks:
      - name: collect facts
        ansible.builtin.setup:
        
      - name: print the facts
        ansible.builtin.debug:
          var: ansible_facts.hostname
