---
  - name: configuring webserver
    hosts: appservers
    tasks:
      - name: installing package
        ansible.builtin.dnf:
          name:
            - httpd
            - firewalld

      - name:  start and enable the service
        ansible.builtin.service:
          name: "{{ item }}"
          state: started
          enabled: true
        loop:
          - httpd
          - firewalld

      - name: configure index.html page
        ansible.builtin.template:
          src: index.html.j2
          dest: /var/www/html/index.html
        notify: restart_webservice

      - name: enable web service in firewall
        ansible.posix.firewalld:
          service: http
          state: enabled
          permanent: true
          immediate: true

    handlers:
      - name: restart_webservice
        ansible.builtin.service:
          name: httpd
          state: restarted
