---
  - name: testing when conditiona 
    hosts: serverd
    tasks:
      - name: check folder existstance
        ansible.builtin.stat:
          path: /home/student1
        register: lichy

      - name: create file
        ansible.builtin.file:
          path: /home/student/fifa.txt
          state: touch
        when: lichy.stat.exists

      - name: print lichy variable
        ansible.builtin.debug:
          var: lichy
