dependencies: []
galaxy_info:
  author: ComplianceAsCode development team
  description: ANSSI-BP-028 (minimal)
  galaxy_tags:
  - system
  - hardening
  - openscap
  - ssg
  - scap
  - security
  - compliance
  - complianceascode
  - redhatofficial
  - redhat
  - rhel10
  - anssibp28minimal
  - anssi
  issue_tracker_url: https://github.com/ComplianceAsCode/content/issues
  license: BSD-3-Clause
  min_ansible_version: 2.9
  platforms:
  - name: EL
    versions:
    - 0
  role_name: rhel10_anssi_bp28_minimal
